spring:
  application:
    name: heroic-bookmarks-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DATABASE_PLATFORM}
logging:
  level:
    org:
      springframework:
        security: DEBUG